# Put config in this section valid for all environments
# Environment specific configs will override this section
all:
  # If disabled set to true, links to Login/Register pages will be hidden,
  # but pages will still be available by direct link
  authentication_disabled: true

# Development env specific configs
development:
  secret_key_base:   xg751p8ngbyKBxVxZ21wXp8098HjQZrM
  devise_secret_key: 8278n3qghIRus1M5quC2Ya54bH99mOgg

  sms_notifier:
    enabled: false
    login: 380503923223
    password: password
    from: RailsCommerce

  mailer:
    default_from: info@domain.com
    host: domain.com
    smtp:
      address: smtp.mandrillapp.com
      user: username
      port: 587
      password: password

# Configs for unit tests
test:
  secret_key_base: xg751p8ngbyKBxVxZ21wXp8098HjQZrM
  devise_secret_key: xg751p8ngbyKBxVxZ21wXp8098HjQZrM

  sms_notifier:
    enabled: false
    login: 380503923223
    password: password
    from: RailsCommerce

  mailer:
    default_from: info@domain.com
    host: localhost:3000
    smtp:
      address: smtp.mandrillapp.com
      user: username
      port: 587
      password: password


# Production config
production:
  #secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  #devise_secret_key: <%= ENV['DEVISE_KEY'] %>
  secret_key_base: 2X86ZBF4g5MzIc4RGH45GAFOI913CGA9
  devise_secret_key: J4963lIx239zOKftAg97akKiDIrny5ft

  sms_notifier:
    enabled: false
    login: 380503923223
    password: password
    from: RailsCommerce

  mailer:
    default_from: info@bsk.com
    host: https://agile-tor-1455.herokuapp.com/
    smtp:
      address: smtp.gmail.com
      user: vishalsmtptest@gmail.com
      port: 587
      password: bskcooler
