# app_key: "va7h72pr2jjytnu"
# app_secret: "7w7gwdc2qhj57x3"
# access_token: "5ghqr3u2762k363j"
# access_token_secret: "miw9yfmcf4fbrcp"
# user_id: "375976753"
# access_type: "app_folder"
client_id: '169467068086-vvnghcmrij5fremneu7glfgla45nat0m.apps.googleusercontent.co'
client_secret: 'vG5Zd4AfuaY1zsoo-nMWOQn-'
access_token: 'ya29._QBN2lfkQTDXf9wJzTZwHHS9oXiISJ05bij-y8CCchsphIUZpdg939ftxu2lRIItWD9q8zQs761vZA'
refresh_token: '1/rL0S6TJR8sUkY_4JEbeyYAD9NKiT4BgM3wk3Nwctygw'
