# app_key: "va7h72pr2jjytnu"
# app_secret: "7w7gwdc2qhj57x3"
# access_token: "5ghqr3u2762k363j"
# access_token_secret: "miw9yfmcf4fbrcp"
# user_id: "375976753"
# access_type: "app_folder"
client_id: '169467068086-23qsqtsnoobdd7ijql8n3ajmq522psq0.apps.googleusercontent.com'
client_secret: 'd1SW7-t6KxjlL8n1OOjL_EyM'
access_token: 'ya29._QAHkGUWbzYflkMI0A2bvxc75mVpWfmHZDdRK53FqF3TAhTAb5Z9w8KmPcftNCftExkVwMuoMiY82Q'
refresh_token: '1/lwHyRNDdIaj_PKvrQcYHA1VIape1Q45dvyOT9s1aHWQMEudVrK5jSpoR30zcRFq6'
